sh-client:
  server:
    web-socket-url: wss://server.test.supcomhub.org/ws

  irc:
    host: irc.test.faforever.com

  vault:
    base-url: http://content.test.faforever.com

  news:
    feed-url: http://direct.faforever.com/news/feed

  replay:
    remote-host: test.faforever.com

  website:
    base-url: https://www.test.faforever.com

  api:
    base-url: https://api.test.supcomhub.org
    client-id: 3bc8282c-7730-11e5-8bcf-feff819cdc9f
    client-secret: 6035bd78-7730-11e5-8bcf-feff819cdc9f

  forged-alliance:
    exe-url: http://content.test.faforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe
